spring:
  main:
    allow-circular-references: true
  security:
    user:
      name: user
      password: user
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/app?createDatabaseIfNotExist=true
    username:  root
    password:  root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
  application:
    name: project-test

server:
  port: 8050
  servlet:
    context-path: /api-projectTest

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: project-test

