server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.99.100
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8761
    register-with-eureka: false
    fetch-registry: false

spring:
  cloud:
    discovery:
      enabled: true

  application:
    name: eureka-server
